pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    environment:
      - SBT_TASK_LIMIT=4
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - if $(git grep -qE "TODO|FIXME" *) ; then
          echo "Please remove TODO or FIXME. Create an issue at GitHub instead." ;
          exit 1 ;
        fi
      - git clone https://github.com/47deg/freestyle.git ; cd freestyle ; sbt freestyleJVM/publishLocal ; cd .. ; rm -rf freestyle
      - sbt ++$SCALA_VERSION ";createHeaders ;test:createHeaders ;test:compile ;doc";
        if $(! git diff --exit-code --quiet) ; then
          echo "Code formatting does not meet the project's standards:" ;
          git --no-pager diff ;
          exit 1 ;
        fi
      - if [ -n "$DRONE_PULL_REQUEST" ] ; then sbt ++$SCALA_VERSION "testOnly -- -l IgnoreOnDrone" ; fi

matrix:
  SCALA_VERSION:
    - 2.12.1
