version: "3.2"

services:
  ## https://discourse.drone.io/t/spinning-up-a-drone-for-integration-testing/2448
  # drone does not have a health service
  # ready:
  #   image: hello-world
  #   depends_on:
  #     drone-server:
  #       condition: service_healthy

  ## http://docs.drone.io/installation/
  drone-server:
    ports:
      - 8000:443
    build: ./drone
#    volumes:
#      - ./drone/build/:/var/lib/drone
    environment:
      - DRONE_ADMIN=${DRONE_ADMIN-fommil}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}

  hello:
    image: cakesolutions/hmonad:2.0
    ports:
      - "1337:80"
    volumes:
      - ./hello/src:/opt/src

volumes:
  drone:
